# Generated by Django 5.1.3 on 2024-11-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cart_price_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='compound',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
